### ISSUE TITLE
华为鸿蒙2.0系统上，文件夹列表为空

### ISSUE THREAD

**Issue by uiuang** [ZLYang110/FileSelector#14]

**Comment by ZLYang110** [comment]
我还没适配华为鸿蒙系统，等我有钱了我也买个适配一下~~~会尽快的~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZLYang110/FileSelector"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月27日(星期一) 下午2:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [ZLYang110/FileSelector] 华为鸿蒙2.0系统上，文件夹列表为空 (#14)





 
Closed #14.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
